# Generated by Django 5.0.6 on 2025-03-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_zibal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=40, unique=True)),
                ('trackId', models.CharField(max_length=255)),
                ('orderId', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Zibal Payments Token',
            },
        ),
    ]
